version: '2'

services:
  devstation-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/workspace:/workspace
      - ../roothome:/root
  devstation:
    image: vochicong/devstation:0.3
    volumes:
      - ~/workspace:/workspace
      - ../roothome:/root
    hostname: devstation
    privileged: true
